"""
Django settings for gemini project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(BASE_DIR )



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e1@s$me!a4-g#^f27k29k2#haz5&2-cbs^-j*=*y8rnmwo$b7f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
# Application definition
SIMPLEUI_HOME_INFO=False
INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testapi',
    'mock',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gemini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gemini.wsgi.application'



# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST':'127.0.0.1',
#         'PORT':'3306',
#         'USER':'root',
#         'PASSWORD':'123456',
#         'NAME':'pacerdb',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # 数据库引擎
        'NAME': 'pacerdb',  # 数据库名，先前创建的
        'USER': os.getenv("MYSQLUSER","root"),     # 用户名，可以自己创建用户ow
        'PASSWORD': os.getenv("MYSQL_ROOT_PASSWORD","123456"),  # 密码
        'HOST': os.getenv("MYSQLLINK","mysql"),  # mysql服务所在的主机ip
        #'HOST': '127.0.0.1',
        'PORT': '3306',         # mysql服务端口
        'OPTIONS': {
                    "init_command": "SET FOREIGN_KEY_CHECKS = 0;",
                    "charset":"utf8mb4"
                },
        'TEST': {
                    'CHARSET' : 'utf8',
                    'COLLATION':'utf8_general_ci'
                }
            }
}
print(os.getenv("MYSQLUSER","root"))
print(os.getenv("MYSQLLINK","mysql"))
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://"+os.getenv("REDISLINK","127.0.0.1")+":6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "PASSWORD": "test123"
        }
    }
}




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# file: setting.py
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
report_url_test='http://127.0.0.1:28080/static/testapi/'
report_url_xs='http://127.0.0.1:28080/static/testapi/'
# report_url_test='http://127.0.0.1:8000/report/'
# eport_url_xs='hhttp://127.0.0.1:8000/report/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
