# Generated by Django 3.2.6 on 2021-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='upload_core',
            field=models.FileField(upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_json',
            field=models.FileField(upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_py',
            field=models.FileField(upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_run',
            field=models.FileField(upload_to='./testapi/case/'),
        ),
    ]
