# Generated by Django 3.2.6 on 2021-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20210927_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportbase',
            fields=[
                ('user_name', models.CharField(max_length=30)),
                ('iterm', models.CharField(max_length=30)),
                ('release', models.CharField(max_length=30)),
                ('modules', models.CharField(max_length=30)),
                ('report_name', models.CharField(max_length=100)),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_url', models.CharField(max_length=300)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reportlist',
            },
        ),
    ]
