# Generated by Django 3.2.6 on 2021-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0003_reportbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relyon',
            fields=[
                ('tool_name', models.CharField(max_length=100)),
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_py', models.FileField(upload_to='./testapi/case/')),
                ('tool_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relyon',
                'verbose_name_plural': '依赖文件',
            },
        ),
    ]
