# Generated by Django 3.2.6 on 2021-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0004_relyon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='case_status',
            field=models.BooleanField(null=True, verbose_name='Execution status'),
        ),
    ]
