# Generated by Django 3.2.6 on 2021-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0006_alter_caselist_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='upload_core',
            field=models.FileField(unique=True, upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_json',
            field=models.FileField(unique=True, upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_py',
            field=models.FileField(unique=True, upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_run',
            field=models.FileField(unique=True, upload_to='./testapi/case/'),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='upload_py',
            field=models.FileField(unique=True, upload_to='./testapi/case/'),
        ),
    ]
