# Generated by Django 3.2.6 on 2021-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0007_auto_20211013_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbase',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='报告ID'),
        ),
        migrations.AlterField(
            model_name='reportbase',
            name='report_name',
            field=models.CharField(max_length=100, verbose_name='报告名称'),
        ),
        migrations.AlterField(
            model_name='reportbase',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='报告时间'),
        ),
        migrations.AlterField(
            model_name='reportbase',
            name='report_url',
            field=models.CharField(max_length=300, verbose_name='报告地址'),
        ),
        migrations.AlterField(
            model_name='reportbase',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
    ]
