# Generated by Django 3.2.6 on 2021-10-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0008_auto_20211014_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='case_name',
            field=models.CharField(max_length=100, verbose_name='测试用例名称'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='upload_run',
            field=models.FileField(unique=True, upload_to='./testapi/case/', verbose_name='运行文件'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
    ]
