# Generated by Django 3.2.6 on 2021-10-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0010_alter_caselist_upload_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MOCK',
                'verbose_name_plural': 'Mock_Server',
            },
        ),
    ]
