# Generated by Django 3.2.6 on 2021-10-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0011_mock_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mock_server',
        ),
    ]
