# Generated by Django 3.2.6 on 2021-10-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('mock_name', models.CharField(max_length=100)),
                ('mock_response', models.JSONField(null=True)),
                ('mock_http', models.CharField(max_length=100)),
                ('mock_path', models.CharField(max_length=100)),
                ('mock_status', models.BooleanField(default=True, verbose_name='Execution status')),
            ],
            options={
                'verbose_name': 'MOCK',
                'verbose_name_plural': 'Mock_Server',
            },
        ),
    ]
